#remote_theme: pmarsceill/just-the-docs

title: test the title
description: A starter template being tested here
theme: just-the-docs

url: https://asjadnaqvi.github.io/testrepo

aux_links:
  Template Repository: https://github.com/asjadnaqvi/testrepo
